name: Node

on:
  push:
    branches: [main]

jobs:
  my-job:
    name: deploy to surge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Deploy
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
        
      - run: npm install -g surge
      - run: surge --project ./ --domain ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
      
